### ISSUE TITLE
random dot colors

### ISSUE THREAD

**Issue by ronraydespain** [antinos/Dimensionality_Reduction-ImageJ#1]
The color of the dots on repeat runs are different.  Can the user choose the colors somehow, so that subsequent runs can be compared?

**Comment by imagejan** [comment]
See also [this forum topic](https://forum.image.sc/t/dimensionality-reduction-plugin-inconsistent-dot-colors-run-to-run/50561?u=imagejan).

**Comment by imagejan** [comment]
How about adding an option to specify a seed when creating the `Random` instance here (i.e. `new Random(seed)`):

https://github.com/antinos/Dimensionality_Reduction-ImageJ/blob/cef7b9ac965bc77bf2735b14b608c5d4fa8eee6a/src/dimred/Umap_.java#L279-L283

and similarly in these places:

https://github.com/antinos/Dimensionality_Reduction-ImageJ/blob/cef7b9ac965bc77bf2735b14b608c5d4fa8eee6a/src/dimred/Tsne_.java#L279

https://github.com/antinos/Dimensionality_Reduction-ImageJ/blob/dd3903eb263ffd235a891b37796d5c8f5ac72ac0/src/dimred/Pca_.java#L298

**Comment by antinos** [comment]
Hi @imagejan ,
I like the seeding idea. My intention was to create a colouring method that was resilient to even large numbers of clusters. I'm not a programmer by profession, so I just sort of intuited the 'random' solution.
Hi @ronraydespain ,
The quickest solution for you may be to use a macro to recolour assigned colours to the plot. Using Jan's idea, this one seems to work:
```javascript
/*
 * Use a seed to recolour a plot. May not work well if multiple plots are open.
 * Make sure the Plot Values table is open before running. Use the 'List' button at the bottom of the plot window.
 */

seed = 1; //Change this number to use a different palette
random("seed", seed);

selectWindow("Plot Values");
headingsString = Table.headings;
headingsArray = split(headingsString, "\t");

index = 0;
//Plot.create("Re-coloured plot", "X", "Y");
for (i = 0; i < headingsArray.length; i+=2) {
	selectWindow("Plot Values");
	xArray = Table.getColumn(headingsArray[i]);
	yArray = Table.getColumn(headingsArray[i+1]);

	r = round(random*230);
	g = round(random*230);
	b = round(random*230);
	rHex = toHex(r);
	gHex = toHex(g);
	bHex = toHex(b);
	hex = "#" + "ff" + "" + pad(rHex) + "" + pad(gHex) + "" + pad(bHex);
	///Plot.add(""+headingsArray[i+1], xArray, yArray);
	Plot.setStyle(index, ""+hex+","+hex+",5.0,Dot");
	index++;
}
Plot.setLimitsToFit();

function pad(n) {
    n = toString(n);
    if(lengthOf(n)==1) n = "0"+n;
    return n;
}
```
I'll update the plugin when I find some time.

**Comment by ronraydespain** [comment]
Thanks antinos.

The macro works well.  I'll mess with it until I get red green blue cyan magenta and black as the first 6 entries.  High contrast colors within the computer color range are best to use.  I'll also mess around with changing the symbol (Dot) and its size as color is often not enough to allow the eye to easily distinguish points.

Ron DeSpain

________________________________

**Comment by antinos** [comment]
Hi @ronraydespain ,
you might also be interested to try changing the native plot options for recolouring groups. Press the 'More>>' button at the bottom of the imagej plot window and then select 'Contents Style....'. From there you should be able to manually set colours for groups. I didn't at first suggest this, as the approach is not really suitable for large numbers of groups.
Kind regards.

**Comment by ronraydespain** [comment]
Thanks antinos

That's a great manual method of changing the color and the shape of the dots.

Ron

________________________________

**Comment by ronraydespain** [comment]
Hello antinos

I want to give you a big pat on the back for your spirit of helpfulness.  I'm a physicist who got interested in AI thru image analysis, so I write macros for medical college students pro bono as a way of giving back.  I'm interested in your profession and how you got into ImageJ macro writing.   I hope we stay in touch.

Ron DeSpain
***@***.***

________________________________

**Comment by antinos** [comment]
@ronraydespain  and @imagejan ,
Thanks for your user feedback and developer advice, respectively. I will now be closing this issue, as I have added the random seed suggestion to v1.0.3 of the plugin, which I have just released.
FYI v1.0.3 also contains a new interactive JavaFx plot visualisation feature for easily relating plot points to corresponding stack images.

Kind regards.
